#!/bin/bash

deploymentSize=${1}

replace_string_in_file() {
  assurefilename=$1
  assuresearchString=$2
  assurereplaceString=$3

  re="s#^.*$assuresearchString.*#$assurereplaceString#"
  sed -i "${re}" "$assurefilename"
  (( "$?" == "0" )) ||
  echo "Could not execute execute sed command replace $assuresearchString with $assurereplaceString in file $assurefilename, terminating install."
}

DIRECTOR_UUID=$(cat ~/workspace/deployments/cf-boshworkspace/deployments/cf-aws-${deploymentSize}.yml | grep director_uuid | awk '{print $2}')
SECURITY_GROUP_ACCESSIBLE_BY_CF_RUNNERS=$(awk 'f{print;f=0} /security_groups/{f=1}' ~/workspace/deployments/cf-boshworkspace/deployments/cf-aws-${deploymentSize}.yml | sed -e 's/^.*- //')
NATS_IP=$(cat ~/workspace/deployments/cf-boshworkspace/.deployments/cf-aws-${deploymentSize}.yml | grep nats -A 1 | grep address | awk '{print $2}')
NATS_PASSWORD=$(cat ~/workspace/deployments/cf-boshworkspace/deployments/cf-aws-${deploymentSize}.yml | grep " secret"  | awk '{print $2}')
DOMAIN=$(cat ~/workspace/deployments/cf-boshworkspace/deployments/cf-aws-${deploymentSize}.yml | grep " domain"  | awk '{print $2}')
EXTERNAL_HOST="cf-containers-broker.${DOMAIN}"
CF_API_URL="http://api.${DOMAIN}"

echo "DIRECTOR_UUID:                            ${DIRECTOR_UUID}"
echo "CF_API_URL:                               ${CF_API_URL}"
echo "EXTERNAL_HOST:                            ${EXTERNAL_HOST}"
echo "NATS_IP:                                  ${NATS_IP}"
echo "SUBNET_ID:                                Get this from AWS Console > VPC > Subnets > 'docker'"
echo "SECURITY_GROUP_ACCESSIBLE_BY_CF_RUNNERS:  ${SECURITY_GROUP_ACCESSIBLE_BY_CF_RUNNERS}"

filename="/home/ubuntu/workspace/deployments/docker-services-boshworkspace/deployments/docker-aws-vpc.yml"
cp "${filename}" "${filename}.orig"
replace_string_in_file $filename "director_uuid: DIRECTOR_UUID"                   "director_uuid: ${DIRECTOR_UUID}"
replace_string_in_file $filename "    cc_api_uri: CF_API_URL"                     "    cc_api_uri: ${CF_API_URL}"
replace_string_in_file $filename "    external_host: EXTERNAL_HOST"               "    external_host: ${EXTERNAL_HOST}"
replace_string_in_file $filename "    password: nats"                             "    password: ${NATS_PASSWORD}"
replace_string_in_file $filename "      - 10.10.3.10"                             "      - ${NATS_IP}"
replace_string_in_file $filename "    - SECURITY_GROUP_ACCESSIBLE_BY_CF_RUNNERS"  "    - ${SECURITY_GROUP_ACCESSIBLE_BY_CF_RUNNERS}"

echo "*********"
echo "$filename has been updated, remember to update the SUBNET_ID"
